### ISSUE TITLE
KeyError: 'ssh_true'

### ISSUE THREAD

**Issue by ErnstPaul** [SWOT-JPL/swotsimulator#32]
Hello, 

As with others before me, I am encountering this error:

/!\ Error occurred while processing grid /Volumes/PaulResearch/EDDYCOMPLETE/swotsimulator/example/swot_output/OREGON_science_grid_p0584.nc
  Traceback (most recent call last):
  
  File "/Users/Paul/opt/anaconda3/lib/python3.9/site-packages/swotsimulator-4.0-py3.9.egg/swotsimulator/mod_parallel.py", line 153, in _operation_wrapper
    operation(msg_queue, *_args, **kwargs)
  
  File "/Users/Paul/opt/anaconda3/lib/python3.9/site-packages/swotsimulator-4.0-py3.9.egg/swotsimulator/run_simulator.py", line 297, in worker_method_swot
    create = mod.create_SWOTlikedata(cycle, list_file, modelbox,
  
  File "/Users/Paul/opt/anaconda3/lib/python3.9/site-packages/swotsimulator-4.0-py3.9.egg/swotsimulator/mod_run.py", line 300, in create_SWOTlikedata
    model_step.read_var(index=model_data.model_index)
  
  File "/Users/Paul/opt/anaconda3/lib/python3.9/site-packages/swotsimulator-4.0-py3.9.egg/swotsimulator/rw_data.py", line 1174, in read_var
    self.input_var['ssh_true'] = self.input_var['ssh_true']*self.SSH_factor
  
KeyError: 'ssh_true'

I am using all settings default with the example data provided in the swotsimulator_largedata repository; the only changed element of any part of the package is the params_example.txt file, where I have placed my working drive file path instead of the example file path. The params file is attached. I also am attempting to use the simulator with LLC4320 and I am getting the same error there too, but I figure that the error must be on some basic level if I am encountering it with the examples provided. 

I appreciate any help you can provide, as I know this issue or ones very similar to it have been addressed before but the solutions were not posted publicly to my knowledge. I apologize if I am mistaken on that front.

Thank you,

Paul Ernst

[params_example.txt](https://github.com/SWOTsimulator/swotsimulator/files/9628855/params_example.txt)

**Comment by lgaultier** [comment]
Hi, 
I will have a look at it today to try to reproduce the error and get back to you on Monday.
Best,
Lucile

**Comment by lgaultier** [comment]
Hi, 
the list_of_file.txt in the swotsimulator_largedata/example/input_fields/ directory is outdated. you should replace it by the one enclosed and I will proof it in the mean time in the simulator during ths week.
[list_of_file.txt](https://github.com/SWOTsimulator/swotsimulator/files/9656060/list_of_file.txt)
Best
Lucile

**Comment by lgaultier** [comment]
You also need to replace the key noise in the parameter file by:
noise = ["altimeter", "karin", "roll_phase", "baseline_dilation", "timing", "wet_troposphere"]
if you don't have the cross-calibration file on your computer.

**Comment by ErnstPaul** [comment]
Hey,

I deeply appreciate the fast responses.

I've taken the steps provided but I'm still seeing the issue occur. 

It appears to be manifesting identically for each individual  output file (/swotsimulator/example/swot_output/OREGON_science_grid_p0015.nc, /swotsimulator/example/swot_output/OREGON_science_grid_p0028.nc, .... /swotsimulator/example/swot_output/OREGON_science_grid_p0584.nc.) 

Let me know if I can provide anything else or help in any other way.

-Paul

**Comment by lgaultier** [comment]
Sorry, from the params_example you shared, you should replace the list_of_file.txt that is located in  home/swotsimulator/example/input_fields by the one that is shared. Such an error happens when the netcdf input files from the model are not found. Is it what you did?
Also I have fixed a small bug so you can pull the last version I have pushed this afternoon

**Comment by ErnstPaul** [comment]
Okay, it is now working, I had placed the file you provided in the wrong location. My desktop is not powerful so it will take some time to run but I believe that it is functioning properly as of this moment. I will close the issue once I have the outputs confirmed on my side. Thank you very much for your assistance through all of this, much appreciated.

**Comment by ErnstPaul** [comment]
Hello,

The simulator is able to reaching pass: 584, cycle: 0001 before a different error occurs:

/!\ Error occurred while processing grid /Volumes/PaulResearch/EDDYCOMPLETE/swotsimulator/example/swot_output/OREGON_science_grid_p0584.nc
  Traceback (most recent call last):
  
  File "/Users/Paul/opt/anaconda3/lib/python3.9/site-packages/swotsimulator-4.0-py3.9.egg/swotsimulator/mod_parallel.py", line 153, in _operation_wrapper
    operation(msg_queue, *_args, **kwargs)
  
  File "/Users/Paul/opt/anaconda3/lib/python3.9/site-packages/swotsimulator-4.0-py3.9.egg/swotsimulator/run_simulator.py", line 307, in worker_method_swot
    mod.save_SWOT(cycle, sgrid, err, p, out_var, time=time,
  
  File "/Users/Paul/opt/anaconda3/lib/python3.9/site-packages/swotsimulator-4.0-py3.9.egg/swotsimulator/mod_run.py", line 542, in save_SWOT
    OutputSWOT.write_data(out_var, roll_err=err.roll,
  
  File "/Users/Paul/opt/anaconda3/lib/python3.9/site-packages/swotsimulator-4.0-py3.9.egg/swotsimulator/rw_data.py", line 399, in write_data
    fid.time_coverage_start = _date.strftime(FORMAT)
  
NameError: name 'FORMAT' is not defined

Is this related to the previous error? I am guessing it is an issue with my params_example.txt not containing a format parameter. Thanks again.

**Comment by lgaultier** [comment]
Yes it is a small bug I have fixed yesterday, just pull the last version: 
> git pull

**Comment by ErnstPaul** [comment]
Thank you, everything works perfectly now. I appreciate your patience.
